services:
    php-fpm:
        build:
            context: .
        volumes:
            - .:/srv/app
        networks:
            - appnet

    caddy:
        image: caddy:latest
        depends_on:
            - php-fpm
        volumes:
            - .:/srv/app
            - caddy_data:/data
        ports:
            - "80:80"
        networks:
            - appnet

networks:
    appnet:

volumes:
    caddy_data:
